In [3]:
import yfinance as yf
import pandas as pd
import numpy as np

import ipywidgets as widgets
from IPython.display import display
from datetime import date, timedelta

import ptm_lib as ptm
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
from_date = date(1928, 1, 1) 
today = date.today()
# ETFs Bonds
tickers = ['TLT','SHY','LQD','JNK','HYG']
file = 'ETFS'
frequency = 'd' 

data = ptm.loadNupdate(tickers, from_date, today, frequency, file)
   
ptm.plot_select(data, tickers)
print(type(data))
ptm.spread_analysis(data, tickers)

Next Timestamp:  2025-07-08 00:00:00
To_date Timestamp: 2025-07-08 00:00:00

interactive(children=(Dropdown(description='Ticker:', options=('TLT', 'SHY', 'LQD', 'JNK', 'HYG'), value='TLT'…

<class 'pandas.core.frame.DataFrame'>

  Ticker                      Description
0    TLT   iShares 20+ Year Treasury Bond
1    SHY   iShares 1-3 Year Treasury Bond
2    LQD  iShares iBoxx $ Investment Grad
3    JNK   SPDR Bloomberg High Yield Bond
4    HYG  iShares iBoxx $ High Yield Corp

interactive(children=(Dropdown(description='Ticker 1', options=('TLT', 'SHY', 'LQD', 'JNK', 'HYG'), value='TLT…

In [12]:
from_date = date(1928, 1, 1) 
today = date.today()
# INDEXES
tickers = ['BAMLC0A1CAAAEY','BAMLC0A4CBBBEY','BAMLH0A3HYCEY','DGS10']
file = 'INDEXES'
frequency = 'd' 

data = ptm.loadNupdate(tickers, from_date, today, frequency, file)

ptm.plot_select(data, tickers)

ptm.spread_analysis(data, tickers)

Next Timestamp:  2025-07-08 00:00:00
To_date Timestamp: 2025-07-08 00:00:00

interactive(children=(Dropdown(description='Ticker:', options=('BAMLC0A1CAAAEY', 'BAMLC0A4CBBBEY', 'BAMLH0A3HY…

,Ticker,Description
0,BAMLC0A1CAAAEY,ICE BofA AAA US Corporate Index Effective Yield
1,BAMLC0A4CBBBEY,ICE BofA BBB US Corporate Index Effective Yield
2,BAMLH0A3HYCEY,ICE BofA CCC & Lower US High Yield Index Effective Yield
3,DGS10,"Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis"

interactive(children=(Dropdown(description='Ticker 1', options=('BAMLC0A1CAAAEY', 'BAMLC0A4CBBBEY', 'BAMLH0A3H…